//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDepartmentsGonA.D.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }
        public string PassportSeries { get; set; }
        public int PassportNum { get; set; }
        public int PlaceIssueOfPassportID { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public string OMS { get; set; }
        public int PlaceOfBirthID { get; set; }
        public int PlaceOfRegistrationID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int StatusID { get; set; }
        public string OrderStudent { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual City City { get; set; }
        public virtual Group Group { get; set; }
        public virtual PlaceIssueOfPassport PlaceIssueOfPassport { get; set; }
        public virtual Status Status { get; set; }
    }
}
