//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDepartmentsGonA.D.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAdress
    {
        public int AdressID { get; set; }
        public int IndexAdress { get; set; }
        public string NameRegion { get; set; }
        public string NameCity { get; set; }
        public string NameStreet { get; set; }
        public int House { get; set; }
        public Nullable<int> Building { get; set; }
        public int Appartament { get; set; }
    }
}
